### ISSUE TITLE
OAuth2 token support

### ISSUE THREAD

**Issue by genau7** [software-mansion-labs/elixir-caldav-client#10]
Hello, are there any plans to extend the auth method to support `Bearer + Token` Authentication header for OAuth2? Seems that `tesla` already supports this so it look like a small change.

**Comment by tomekzaw** [comment]
Hello, this feature would be very desirable and hopefully quite easy to implement (just as you have mentioned). I'm quite busy recently but if you have any idea how this can be done, feel free to open a PR 😄

**Comment by boonious** [comment]
👋 hey, a PR has now been created by @duderman: https://github.com/software-mansion-labs/elixir-caldav-client/pull/11 , please take a look TA.

**Comment by tomekzaw** [comment]
Done by @duderman in #11.
