### ISSUE TITLE
Alternative time zone databases

### ISSUE THREAD

**Issue by mathieuprog** [software-mansion-labs/elixir-caldav-client#9]
Thank you for this great library 👍

The Readme says `tzdata` library is recommended, however it is the most bugged time zone database at present. See https://elixirforum.com/t/29358
It also crashes the application for some datetimes.

Two bug-free time zone libraries are:
* https://github.com/mathieuprog/tz  (mine)
* https://github.com/hrzndhrn/time_zone_info

**Comment by tomekzaw** [comment]
Hello! We use `tzdata` only as optional dependency for local testing. The library itself does not depend on any specific time zone database. If you think that these unit tests would benefit from upgrading to an alternative time zone database, feel free to submit a PR 😄
